<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'kode_produk' => 'PRD-001',
                'nama_produk' => 'Plastik Kresek Merah 15x30',
                'category_id' => 1,
                'supplier_id' => 1,
                'satuan' => 'Pax',
                'harga_beli' => 6000,
                'harga_jual' => 7500,
                'stok' => 0, // Will be computed dynamically by transaction seeders!
                'minimum_stok' => 10,
                'foto' => null,
                'deskripsi' => 'Kantong plastik kresek warna merah ukuran sedang 15x30 cm.',
            ],
            [
                'kode_produk' => 'PRD-002',
                'nama_produk' => 'Plastik Kresek Putih 24x40',
                'category_id' => 1,
                'supplier_id' => 1,
                'satuan' => 'Pax',
                'harga_beli' => 11000,
                'harga_jual' => 13500,
                'stok' => 0,
                'minimum_stok' => 10,
                'foto' => null,
                'deskripsi' => 'Kantong plastik kresek warna putih tebal ukuran besar 24x40 cm.',
            ],
            [
                'kode_produk' => 'PRD-003',
                'nama_produk' => 'Plastik Kresek Hitam 35x55',
                'category_id' => 1,
                'supplier_id' => 2,
                'satuan' => 'Pax',
                'harga_beli' => 18000,
                'harga_jual' => 22000,
                'stok' => 0,
                'minimum_stok' => 15,
                'foto' => null,
                'deskripsi' => 'Kantong plastik kresek hitam jumbo tebal untuk sampah atau barang berat.',
            ],
            [
                'kode_produk' => 'PRD-004',
                'nama_produk' => 'Plastik PP Bening 10x20',
                'category_id' => 2,
                'supplier_id' => 2,
                'satuan' => 'Pack',
                'harga_beli' => 4000,
                'harga_jual' => 5000,
                'stok' => 0,
                'minimum_stok' => 20,
                'foto' => null,
                'deskripsi' => 'Plastik PP bening tebal 0.3 mm untuk kemasan snack atau makanan kering.',
            ],
            [
                'kode_produk' => 'PRD-005',
                'nama_produk' => 'Plastik PP Wayang 12x25',
                'category_id' => 2,
                'supplier_id' => 3,
                'satuan' => 'Pack',
                'harga_beli' => 5500,
                'harga_jual' => 7000,
                'stok' => 0,
                'minimum_stok' => 20,
                'foto' => null,
                'deskripsi' => 'Plastik PP merk Wayang ukuran 12x25 cm, mengkilap dan kuat.',
            ],
            [
                'kode_produk' => 'PRD-006',
                'nama_produk' => 'Plastik HDPE Tomat 20x30',
                'category_id' => 3,
                'supplier_id' => 3,
                'satuan' => 'Pack',
                'harga_beli' => 8500,
                'harga_jual' => 10500,
                'stok' => 0,
                'minimum_stok' => 15,
                'foto' => null,
                'deskripsi' => 'Plastik HDPE cap Tomat, ramah makanan dan ulet.',
            ],
            [
                'kode_produk' => 'PRD-007',
                'nama_produk' => 'Gulungan Roll HDPE Bening',
                'category_id' => 3,
                'supplier_id' => 4,
                'satuan' => 'Roll',
                'harga_beli' => 45000,
                'harga_jual' => 55000,
                'stok' => 0,
                'minimum_stok' => 5,
                'foto' => null,
                'deskripsi' => 'Plastik roll tipis HDPE untuk buah sayur supermarket.',
            ],
            [
                'kode_produk' => 'PRD-008',
                'nama_produk' => 'Plastik PE Bening Es 10x20',
                'category_id' => 4,
                'supplier_id' => 4,
                'satuan' => 'Pack',
                'harga_beli' => 6200,
                'harga_jual' => 7800,
                'stok' => 0,
                'minimum_stok' => 20,
                'foto' => null,
                'deskripsi' => 'Plastik PE lentur tahan dingin untuk pembuatan es batu.',
            ],
            [
                'kode_produk' => 'PRD-009',
                'nama_produk' => 'Plastik PE Cor Lebar 1m',
                'category_id' => 4,
                'supplier_id' => 5,
                'satuan' => 'Meter',
                'harga_beli' => 12000,
                'harga_jual' => 15000,
                'stok' => 0,
                'minimum_stok' => 30,
                'foto' => null,
                'deskripsi' => 'Plastik PE tebal meteran untuk penutup cor bangunan atau pembungkus barang besar.',
            ],
            [
                'kode_produk' => 'PRD-010',
                'nama_produk' => 'Sedotan Hitam Steril Ulir',
                'category_id' => 5,
                'supplier_id' => 5,
                'satuan' => 'Pack',
                'harga_beli' => 7500,
                'harga_jual' => 9500,
                'stok' => 0,
                'minimum_stok' => 15,
                'foto' => null,
                'deskripsi' => 'Sedotan steril ulir hitam isi 100 pcs, masing-masing dibungkus plastik.',
            ],
            [
                'kode_produk' => 'PRD-011',
                'nama_produk' => 'Sedotan Bubble Warna-Warni',
                'category_id' => 5,
                'supplier_id' => 1,
                'satuan' => 'Pack',
                'harga_beli' => 9000,
                'harga_jual' => 11500,
                'stok' => 0,
                'minimum_stok' => 15,
                'foto' => null,
                'deskripsi' => 'Sedotan diameter besar (12mm) untuk boba dan minuman jelly.',
            ],
            [
                'kode_produk' => 'PRD-012',
                'nama_produk' => 'Gelas Plastik Cup 16oz',
                'category_id' => 6,
                'supplier_id' => 2,
                'satuan' => 'Slop',
                'harga_beli' => 14000,
                'harga_jual' => 17500,
                'stok' => 0,
                'minimum_stok' => 25,
                'foto' => null,
                'deskripsi' => 'Gelas cup plastik bening ukuran 16oz isi 50 pcs (belum termasuk tutup).',
            ],
            [
                'kode_produk' => 'PRD-013',
                'nama_produk' => 'Gelas Plastik Cup 22oz Tebal',
                'category_id' => 6,
                'supplier_id' => 3,
                'satuan' => 'Slop',
                'harga_beli' => 19000,
                'harga_jual' => 24000,
                'stok' => 0,
                'minimum_stok' => 20,
                'foto' => null,
                'deskripsi' => 'Gelas cup plastik bening jumbo tebal ukuran 22oz isi 50 pcs.',
            ],
            [
                'kode_produk' => 'PRD-014',
                'nama_produk' => 'Mika Box Makanan 3A',
                'category_id' => 7,
                'supplier_id' => 4,
                'satuan' => 'Pack',
                'harga_beli' => 12500,
                'harga_jual' => 16000,
                'stok' => 0,
                'minimum_stok' => 15,
                'foto' => null,
                'deskripsi' => 'Kotak mika bening ukuran 3A isi 100 pcs untuk wadah kue basah/nasi.',
            ],
            [
                'kode_produk' => 'PRD-015',
                'nama_produk' => 'Box Thinwall Bulat 500ml',
                'category_id' => 7,
                'supplier_id' => 5,
                'satuan' => 'Pack',
                'harga_beli' => 28000,
                'harga_jual' => 35000,
                'stok' => 0,
                'minimum_stok' => 10,
                'foto' => null,
                'deskripsi' => 'Wadah makan plastik thinwall bulat / mangkok isi 25 pcs microwave safe.',
            ],
            [
                'kode_produk' => 'PRD-016',
                'nama_produk' => 'Sendok Plastik Putih Bebek',
                'category_id' => 8,
                'supplier_id' => 1,
                'satuan' => 'Pack',
                'harga_beli' => 6500,
                'harga_jual' => 8000,
                'stok' => 0,
                'minimum_stok' => 10,
                'foto' => null,
                'deskripsi' => 'Sendok plastik putih model bebek sekali pakai isi 100 pcs.',
            ],
            [
                'kode_produk' => 'PRD-017',
                'nama_produk' => 'Garpu Plastik Bening isi 50',
                'category_id' => 8,
                'supplier_id' => 2,
                'satuan' => 'Pack',
                'harga_beli' => 7000,
                'harga_jual' => 9000,
                'stok' => 0,
                'minimum_stok' => 10,
                'foto' => null,
                'deskripsi' => 'Garpu makan plastik bening standar isi 50 pcs.',
            ],
            [
                'kode_produk' => 'PRD-018',
                'nama_produk' => 'Kertas Pembungkus Nasi Gajah',
                'category_id' => 9,
                'supplier_id' => 3,
                'satuan' => 'Pack',
                'harga_beli' => 21000,
                'harga_jual' => 26000,
                'stok' => 0,
                'minimum_stok' => 12,
                'foto' => null,
                'deskripsi' => 'Kertas laminasi minyak pembungkus nasi cap Gajah isi 250 lembar.',
            ],
            [
                'kode_produk' => 'PRD-019',
                'nama_produk' => 'Karet Gelang Kuning Pentil',
                'category_id' => 10,
                'supplier_id' => 4,
                'satuan' => 'Kantong',
                'harga_beli' => 32000,
                'harga_jual' => 40000,
                'stok' => 0,
                'minimum_stok' => 8,
                'foto' => null,
                'deskripsi' => 'Karet gelang pentil warna kuning premium elastis kuat isi 1 kg.',
            ],
            [
                'kode_produk' => 'PRD-020',
                'nama_produk' => 'Karet Gelang Campur Warna',
                'category_id' => 10,
                'supplier_id' => 5,
                'satuan' => 'Kantong',
                'harga_beli' => 27000,
                'harga_jual' => 34000,
                'stok' => 0,
                'minimum_stok' => 8,
                'foto' => null,
                'deskripsi' => 'Karet gelang campur warna standar isi 1 kg.',
            ],
        ];

        foreach ($products as $prod) {
            Product::create($prod);
        }
    }
}
